security:
    encoders:
        Gitonomy\Bundle\CoreBundle\Entity\User:
            algorithm:        sha512
            encode-as-base64: true
            iterations:       5

    providers:
        entity:
            entity: { class: Gitonomy\Bundle\CoreBundle\Entity\User, property: "username" }

    firewalls:
        main:
            security:   true
            form_login:
                login_path:          splash_login
                check_path:          splash_loginCheck
                default_target_path: splash_login
            remember_me:
                key:      %remember_secret%
                lifetime: 31536000
                path:     /
                domain:   ~
            logout:
                path:   splash_logout
                target: splash_login
            anonymous: true
