#!/bin/sh

# Check the context informations
if [ -z "$GITONOMY_USER" -o -z "$GITONOMY_PROJECT" ]; then
    echo >&2 "Context informations missing"
    exit 1
fi

# Gitonomy console
command="php `php -r 'echo realpath(dirname(dirname(dirname(__DIR__))));'`/console"

check_reference()
{
	BEFORE="$(git rev-parse $1)"
	AFTER="$(git rev-parse $2)"
	REFERENCE="$3"

	if [ "$AFTER" = "0000000000000000000000000000000000000000" ]; then
        REQUEST="GIT_DELETE"
    else if [ "$BEFORE" = "0000000000000000000000000000000000000000" ]; then
        REQUEST="GIT_WRITE"
    else if [ "$BEFORE" != "$(git merge-base $BEFORE $AFTER)" ]; then
        REQUEST="GIT_FORCE"
    else
        REQUEST="GIT_WRITE"
    fi fi fi

    $command gitonomy:git-permission-check "$GITONOMY_PROJECT" "$GITONOMY_USER" "$REQUEST" "$REFERENCE"
    if [ "$?" != 0 ]; then
        cat >&2 <<END



                  .
                 /'
                //
            .  //
            |\//7
           /' " \\
          .   . .
          | (    \\     '._
          |  '._  '    '. '
          /    \\'-'_---. ) )
         .              :.'
         |               \\
    -----------------------------
          Defensive unicorn
               says no
    -----------------------------

END
        exit 1
    fi
}

while read before after reference
do
    check_reference $before $after $reference
done
