#!/bin/sh

# Check the context informations
if [ -z "$GITONOMY_USER" -o -z "$GITONOMY_PROJECT" ]; then
    echo >&2 "Context informations missing"
    exit 1
fi

# Gitonomy console
command="php `php -r 'echo realpath(dirname(dirname(dirname(__DIR__))));'`/console"

check_reference()
{
	BEFORE="$(git rev-parse $1)"
	AFTER="$(git rev-parse $2)"
	REFERENCE="$3"

	if [ "$AFTER" = "0000000000000000000000000000000000000000" ]; then
        REQUEST="GIT_DELETE"
    else if [ "$BEFORE" = "0000000000000000000000000000000000000000" ]; then
        REQUEST="GIT_WRITE"
    else if[ "$BEFORE" != "$(git merge-base $BEFORE $AFTER)" ]; then
        REQUEST="GIT_FORCE"
    else
        REQUEST="GIT_WRITE"
    fi

    $command gitonomy:permission-check --project="$GITONOMY_PROJECT" "$GITONOMY_USER" "$REQUEST" "$REFERENCE"
    if [ "$?" != 0 ]; then
        echo  >&2 "Computer says no"
        exit 1
    fi
}

while read before after reference
do
    check_reference $before $after $reference
done
